name: Build and Test

on:
 push:
    branches: [ main ]
 pull_request:
    branches: [ main ]

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up CMake
      uses: actions/setup-cmake@v2

    - name: Build
      run: cmake --build . --config Release

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: executable
        path: Release/decorator
    - name: Run tests
      run: ctest --output-on-failure -C Release

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: |
          Testing/Temporary/LastTest.log
          Testing/Temporary/LastTestsFailed.log

